### ISSUE TITLE
No ShadowTextureRenderer found.

### ISSUE THREAD

**Issue by JeanLFraga** [nyahoon-games/DynamicShadowProjectorExtensionForLWRP#1]
After selecting DynamicShadowProjectorRenderer asset as a custom render in LWRP asset, all objects stop being drawn.
It appears to be looking for a ShadowTextureRenderer in the camera object, after not finding it stops rendering.
For test sake, I tried to add the ShadowTextureRenderer in the camera, appears to remove Unity's Camera script and still doesn't work.

Versions:
Unity - 2019.2.18f
LWRP - 6.9.2
Projector For LWRP - Latest
Dynamic Shadow Projector - Latest

**Comment by takaokato** [comment]
Hi,

DynamicShadowProjectorRenderer cannot be a default renderer. It works only for cameras attached to dynamic shadow projector objects (they are hidden by default). You don’t need to do anything for DynamicShadowProjectorRenderer, it will be automatically used by ShadowTextureRenderer.

Best Regards,
Takao Kato
Nyahoon Games Pte. Ltd.

**Comment by JeanLFraga** [comment]
Hi, thanks for the quick response.
Okay, I made the setup using the Custom Renderer from the Projector For LWRP and it's working now.

Thank you for the help and the great asset 😃
