### ISSUE TITLE
Any plans for iOS Metal?

### ISSUE THREAD

**Issue by VrabelJan** [nyahoon-games/DynamicShadowProjectorExtensionForLWRP#3]
Is is possible to use this DynamicShadow feature for iOS on Metal? Unfortunately Unity I am using (2021.2.18f1) doesnt have switch for OpenGL anymore and on Metal there is error, that some shaders are not supported. I am not shader expert at all, but i believe, GLSL is something only for OpenGL, so I am curious, if you guys are planing support for Metal.
Thnx a lot. 

Cool tool btw, I am really impressed with visual results in Unity Editor!!! You did amazing job!!!

**Comment by takaokato** [comment]
Hi, thank you for using Dynamic Shadow Projector.

There are some GLSL shaders in this project, but they are used only for checking OpenGL device's capability. Dynamic Shadow Projector should work on non-OpenGL devices.

What errors did you see actually?

**Comment by VrabelJan** [comment]
Damn!!! So sorry, after you wrote, it should works on non-OpenGL devices, i went through everything step by step again and realised, i had different quality settings for iOS device, where Projector Renderer Feature was not attached to renderer in this quality level (facePalm).
You saved my day with your information :)
